CREATE DATABASE "kursDb"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Russian_Russia.1251'
    LC_CTYPE = 'Russian_Russia.1251'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

CREATE SCHEMA users
    AUTHORIZATION postgres;

CREATE TABLE users.users
(
    id_user integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    n_passport character(9) COLLATE pg_catalog."default" NOT NULL,
    idn_passport character(14) COLLATE pg_catalog."default" NOT NULL,
    n_phone character(20) COLLATE pg_catalog."default" NOT NULL,
    email character(70) COLLATE pg_catalog."default" NOT NULL,
    password character(50) COLLATE pg_catalog."default" NOT NULL,
    birthday character(50) COLLATE pg_catalog."default" NOT NULL,
    registrday character(50) COLLATE pg_catalog."default" NOT NULL,
    isadmin boolean NOT NULL,
    login character(50) COLLATE pg_catalog."default" NOT NULL,
    name character(50) COLLATE pg_catalog."default" NOT NULL,
    lastname character(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id_user),
    CONSTRAINT uniqevalues1 UNIQUE (login),
    CONSTRAINT uniqevalues2 UNIQUE (n_passport),
    CONSTRAINT uniqevalues3 UNIQUE (idn_passport)
)
TABLESPACE pg_default;
ALTER TABLE users.users
    OWNER to postgres;

CREATE TABLE users.vehicleapplications
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 100000 MINVALUE 100000 MAXVALUE 2147483647 CACHE 1 ),
    id_user integer NOT NULL,
    term bigint NOT NULL,
    beginterm character(50) COLLATE pg_catalog."default" NOT NULL,
    insurancefee character(30) COLLATE pg_catalog."default" NOT NULL,
    typeofpayment character(30) COLLATE pg_catalog."default" NOT NULL,
    executepersson character(30) COLLATE pg_catalog."default" NOT NULL,
    drivingexperience integer NOT NULL,
    vehiclemodel character(50) COLLATE pg_catalog."default" NOT NULL,
    registersign character(8) COLLATE pg_catalog."default" NOT NULL,
    bodynumber character(6) COLLATE pg_catalog."default" NOT NULL,
    enginedisplacement character(10) COLLATE pg_catalog."default" NOT NULL,
    liftingcapacity character(10) COLLATE pg_catalog."default" NOT NULL,
    numberofseats integer NOT NULL,
    enginepower integer NOT NULL,
    roadaccidents integer NOT NULL,
    yearofcreated integer NOT NULL,
    battery character(10) COLLATE pg_catalog."default" NOT NULL,
    processed boolean NOT NULL,
    CONSTRAINT vehicleapplications_pkey PRIMARY KEY (id),
    CONSTRAINT constr1 UNIQUE (registersign),
    CONSTRAINT vehicle_user FOREIGN KEY (id_user)
        REFERENCES users.users (id_user) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)
TABLESPACE pg_default;
ALTER TABLE users.vehicleapplications
    OWNER to postgres;

CREATE TABLE users.propertyapplications
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 200000 MINVALUE 200000 MAXVALUE 2147483647 CACHE 1 ),
    id_user integer NOT NULL,
    term bigint NOT NULL,
    beginterm character(50) COLLATE pg_catalog."default" NOT NULL,
    insurancefee character(30) COLLATE pg_catalog."default" NOT NULL,
    typeofpayment character(30) COLLATE pg_catalog."default" NOT NULL,
    executepersson character(30) COLLATE pg_catalog."default" NOT NULL,
    address character(100) COLLATE pg_catalog."default" NOT NULL,
    area integer NOT NULL,
    rooms integer NOT NULL,
    yearofcreated integer NOT NULL,
    propfloor integer NOT NULL,
    doors integer NOT NULL,
    steeldoor boolean NOT NULL,
    codelock boolean NOT NULL,
    unfiresystem boolean NOT NULL,
    securitysystem boolean NOT NULL,
    unfirematerial boolean NOT NULL,
    highrisk boolean NOT NULL,
    processed boolean NOT NULL,
    CONSTRAINT propertyapplications_pkey PRIMARY KEY (id),
    CONSTRAINT constr2 UNIQUE (address),
    CONSTRAINT property_user FOREIGN KEY (id_user)
        REFERENCES users.users (id_user) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)
TABLESPACE pg_default;
ALTER TABLE users.propertyapplications
    OWNER to postgres;

CREATE TABLE users.healthapplications
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 300000 MINVALUE 300000 MAXVALUE 2147483647 CACHE 1 ),
    id_user integer NOT NULL,
    term bigint NOT NULL,
    beginterm character(50) COLLATE pg_catalog."default" NOT NULL,
    insurancefee character(30) COLLATE pg_catalog."default" NOT NULL,
    typeofpayment character(30) COLLATE pg_catalog."default" NOT NULL,
    executepersson character(30) COLLATE pg_catalog."default" NOT NULL,
    harmhappend boolean NOT NULL,
    healthhappend boolean NOT NULL,
    invalidhappend boolean NOT NULL,
    deathill boolean NOT NULL,
    covid boolean NOT NULL,
    sport boolean NOT NULL,
    relax boolean NOT NULL,
    invalid12 boolean NOT NULL,
    processed boolean NOT NULL,
    CONSTRAINT healthapplications_pkey PRIMARY KEY (id),
    CONSTRAINT constr3 UNIQUE (id_user),
    CONSTRAINT health_user FOREIGN KEY (id_user)
        REFERENCES users.users (id_user) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)
TABLESPACE pg_default;
ALTER TABLE users.healthapplications
    OWNER to postgres;

CREATE TABLE users.contracts
(
    id integer NOT NULL,
    id_admin integer NOT NULL,
    dateodpay integer NOT NULL,
    summofpayment character(50) COLLATE pg_catalog."default" NOT NULL,
    paymonthcost character(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT contracts_pkey PRIMARY KEY (id),
    CONSTRAINT user_constr FOREIGN KEY (id_admin)
        REFERENCES users.users (id_user) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)
TABLESPACE pg_default;
ALTER TABLE users.contracts
    OWNER to postgres;

CREATE TABLE users.techsupport
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 200000 MINVALUE 200000 MAXVALUE 2147483647 CACHE 1 ),
    id_user integer NOT NULL,
    question text COLLATE pg_catalog."default" NOT NULL,
    closed boolean NOT NULL,
    id_admin integer,
    answer text COLLATE pg_catalog."default",
    CONSTRAINT techsupport_pkey PRIMARY KEY (id),
    CONSTRAINT tech_to_users FOREIGN KEY (id_user)
        REFERENCES users.users (id_user) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)
TABLESPACE pg_default;
ALTER TABLE users.techsupport
    OWNER to postgres;
